#!/bin/bash

#SBATCH --job-name=virian                 # Job name
#SBATCH --output=jobs/logs/tokeize-%j.out # Name of output file
#SBATCH --cpus-per-task=1                 # Schedule one core
#SBATCH --time=01:00:00                   # Run time (hh:mm:ss)
#SBATCH --partition=brown                 # red of brown
#SBATCH --mem-per-cpu=8000                # memory per cpu


source env/bin/activate
python main.py --tokenize
